/*
 * JS for startScreen generated by Appery.io
 */

Appery.getProjectGUID = function() {
    return '61027b34-50f6-4b82-ad83-e9290f46e419';
};

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}];

startScreen_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobiletextinput_3': 'startScreen_mobiletextinput_3',
        'mobilebutton_2': 'startScreen_mobilebutton_2',
        'mobilelink_4': 'startScreen_mobilelink_4'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=footer]").css("bottom", "-36px");
    }

    Appery.CurrentScreen = 'startScreen';

    /*
     * Nonvisual components
     */
    var datasources = [];

    restservice1 = new Appery.DataSource(RESTService, {
        'onComplete': function(jqXHR, textStatus) {

            Appery.refreshScreenFormElements("startScreen");
        },
        'onSuccess': function(data) {
            localStorage.setItem('url', '');
            setAttribute_('startScreen_mobilelink_4', 'href', localStorage.getItem('url'));
            $('[id="startScreen_mobilelink_4"]').refresh();
            toggle('startScreen_mobilelink_4', 'mob', 'true');
            alert(url);
        },
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['url'],
            'ID': 'mobilelink_4',
            'ATTR': '@'
        }],
        'requestMapping': [{
            'PATH': ['price'],
            'TYPE': 'STRING',
            'ID': 'mobiletextinput_3',
            'ATTR': 'value'
        }, {
            'PATH': ['currency'],
            'TYPE': 'STRING',
            'ATTR': 'USD'
        }, {
            'PATH': ['Accept'],
            'TYPE': 'STRING',
            'HEADER': true,
            'ATTR': 'application/json'
        }, {
            'PATH': ['appery-proxy-url'],
            'HEADER': true,
            'ATTR': 'https://EAk9NXcFLgQ1k9ZcMdhg5MPMV7Ww762iwYWX9Kxk8:@bitpay.com/api/invoice'
        }, {
            'PATH': ['appery-transformation'],
            'HEADER': true,
            'ATTR': 'checkTunnel'
        }, {
            'PATH': ['appery-key'],
            'HEADER': true,
            'ATTR': '1393184678624'
        }, {
            'PATH': ['appery-rest'],
            'HEADER': true,
            'ATTR': '90493a28-5d3a-4283-a28b-477dd1f1d04d'
        }]
    });

    datasources.push(restservice1);

    /*
     * Events and handlers
     */

    // Before Show
    var startScreen_beforeshow = function() {
            Appery.CurrentScreen = "startScreen";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var startScreen_onLoad = function() {
            startScreen_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            startScreen_deviceEvents();
            startScreen_windowEvents();
            startScreen_elementsEvents();
        };

    // screen window events
    var startScreen_windowEvents = function() {

            $('#startScreen').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var startScreen_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var startScreen_elementsExtraJS = function() {
            // screen (startScreen) extra code

        };

    // screen elements handler
    var startScreen_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#startScreen_mobilecontainer1 [name="mobilebutton_2"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        try {
                            restservice1.execute({})
                        } catch (ex) {
                            console.log(ex.name + '  ' + ex.message);
                            hideSpinner();
                        };

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="mobilebutton_2"]');

        };

    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        startScreen_beforeshow();
    });

    if (runBeforeShow) {
        startScreen_beforeshow();
    } else {
        startScreen_onLoad();
    }
};

$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Appery.processSelectMenu($(this));
    startScreen_js();
});